### ISSUE TITLE
Repo TODO List

### ISSUE THREAD

**Issue by sithyrys522** [sithyrys522/sithyrys522.github.io#1]
- [ ] Bring Jekyll to Github Pages Repo
- [ ] Finish Jekyll tutorial
- [ ] Convert tutorial site to DnD Blog Site
- [ ] *Maybe* add some form of automated deployment. (CI/CD I believe were the buzzwords)
- [ ] Possibly add Netlify CMS or similiar since I won't be the one writing the actual Blog posts routinely.
